Repository jenkinsci/ssh-agent-plugin, pull requests merged in 2020-01, with the labels that each got.

#32 Use new Core `WorkspaceList.tempDir` API as per TODO item.
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentStepExecution.java
Labels: chore

#29 Do not use jnr-posix
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/jna/AgentServer.java
Labels: chore

#34 [INFRA-2412] Prepare for Release Drafter & migrate from wiki
  .github/release-drafter.yml
  README.md
  docs/images/Screen_Shot_2012-10-26_at_11.54.21.png
  docs/images/Screen_Shot_2012-10-26_at_12.25.04.png
  docs/images/Screen_Shot_2012-10-26_at_12.26.13.png
  docs/old-changelog.md
  pom.xml
Labels: documentation

#33 [JENKINS-59259] Fix durability crash in sshAgent step
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/RemoteAgent.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentBuildWrapper.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentStepExecution.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/exec/ExecRemoteAgent.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/jna/JNRRemoteAgent.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/mina/MinaRemoteAgent.java
  src/test/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentStepWorkflowTest.java
Labels: bug

#35 Fix serialization problems
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/LauncherProvider.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/RemoteAgent.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/RemoteAgentFactory.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentBuildWrapper.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentStepExecution.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/exec/ExecRemoteAgent.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/exec/ExecRemoteAgentFactory.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/jna/JNRRemoteAgent.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/jna/JNRRemoteAgentFactory.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/mina/MinaRemoteAgent.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/mina/MinaRemoteAgentFactory.java
Labels: bug
