Repository jenkinsci/ssh-agent-plugin, pull requests merged in 2021-06, with the labels that each got.

#54 [JENKINS-60902] adds the dependency of the Apache Mina sshd 2.5.1
  pom.xml
  src/test/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentBase.java
Labels: dependencies

#51 [JENKINS-65457] Add description to credentials and ignoreMissing argu…
  src/main/resources/com/cloudbees/jenkins/plugins/sshagent/SSHAgentStep/help-credentials.html
  src/main/resources/com/cloudbees/jenkins/plugins/sshagent/SSHAgentStep/help-ignoreMissing.html
Labels: documentation

#50 Show launcher output on remote agent exec failure
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/exec/ExecRemoteAgent.java
Labels: enhancement

#57 Update README.md - Jenkinsfile Example - With keyscan to prevent "Host key verification failed" errors
  README.md
Labels: documentation
