Repository jenkinsci/ssh-agent-plugin, pull requests merged in 2022-05, with the labels that each got.

#78 Move away from deprecated Release Drafter App
  .github/workflows/release-drafter.yml
Labels: chore

#83 Bump parent, BOM, `sshd-core` dep
  pom.xml
  src/main/resources/index.jelly
  src/test/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentBase.java
Labels: dependencies

#85 Enable CD
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: developer
