Repository jenkinsci/ssh-agent-plugin, pull requests merged in 2022-09, with the labels that each got.

#89 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#91 [chore] Replace sshd-core with mina-sshd-api-core plugin
  pom.xml
Labels: dependencies

#105 Use KeyUtils.RSA_ALGORITHM
  src/test/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentBase.java
Labels: chore

#104 Replace some deprecated APIs
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/RemoteAgent.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentBuildWrapper.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentStep.java
  src/main/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentStepExecution.java
  src/test/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentBuildWrapperTest.java
  src/test/java/com/cloudbees/jenkins/plugins/sshagent/SSHAgentStepWorkflowTest.java
Labels: chore

#102 Enable syntax colouring and update formatting of example
  README.md
Labels: documentation

#103 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore
